//! host / none モードの `--dns` を `resolv.conf` へ反映する（NET-12・NET-6・TASK-185.4・#347・ERR-1・MS-8）。
//!
//! CLI / stack が受け取った `--dns` の生入力を、runtime がコンテナごとの状態ディレクトリ配下に用意した
//! `resolv.conf` のパスへ書き出す入口。`/etc/resolv.conf` への bind mount は core / oci 側の責務で、
//! rootfs 内のパスは本モジュールでは組み立てない（パストラバーサル経路を作らない）。
//!
//! - host: 検証済みの値を `nameserver` 行として書く。
//! - none: loopback（`127.0.0.0/8`・`::1`）以外はコンテナ作成前に `INVALID_ARGUMENT` で拒否し、ファイルに
//!   一切触れない。loopback は書くが到達性は保証・検証しない（NET-6）。IPv4 射影 `::ffff:127.0.0.1` は
//!   `IpAddr::is_loopback()` が false のため fail-closed で拒否する。
//! - bridge: 未実装（REPAIR-3）。DNS ヘルパーの上流転送は TASK-185.3（#346）、軽量運用（NET-8）の直接書き込みは
//!   TASK-146.2（#336）。bridge では nameserver を決して書かない。
//!
//! 検証は全件を終えてから書き込む all-or-nothing。ファイルへは `IpAddr` の表記のみを書き、利用者の
//! 生文字列は到達しない（改行注入で `options` / `search` 行を差し込めない）。
//!
//! 契約: 書き込み先パスの親ディレクトリは runtime 管理下の信頼できる場所であること（祖先 symlink の検証は
//! 呼び出し側の前提）。最終要素が symlink でも追従せず置換する。

use std::ffi::OsString;
use std::fs::OpenOptions;
use std::io::Write;
use std::net::IpAddr;
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use super::{InputViolation, parse_ip_addr};
use crate::error::{NetError, NetErrorCode};
use crate::network_mode::NetworkMode;

/// `--dns` の上限件数（無制限確保の防止）。glibc は先頭 3 件（MAXNS）しか使わない。
pub const MAX_DNS_SERVERS: usize = 32;

/// 生成ファイルの先頭に置く固定コメント。
const HEADER: &str = "# Generated by fandhe-container (NET-12)\n";

/// 検証済みの `resolv.conf` 生成計画（host / none 用）。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvConfPlan {
    nameservers: Vec<IpAddr>,
}

/// [`apply_dns`] の結果。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum DnsApplyOutcome {
    /// `count` 件の nameserver を書き込んだ。
    Written { count: usize },
    /// 書き込む対象がなかった（`--dns` 未指定）。ファイルには触れていない。
    NotRequested,
}

impl ResolvConfPlan {
    /// モードと `--dns` 生入力から計画を作る（副作用なし）。
    ///
    /// 空入力は `Ok(None)`（no-op。bridge でも同様）。bridge で値がある場合は `UNIMPLEMENTED`。
    /// 1 件でも不正なら `Err` で、呼び出し側はファイル操作に進まない。
    pub fn for_mode(mode: NetworkMode, dns: &[&str]) -> Result<Option<Self>, NetError> {
        if dns.len() > MAX_DNS_SERVERS {
            return Err(NetError::new(
                NetErrorCode::InvalidArgument,
                "too many --dns servers",
            ));
        }
        if dns.is_empty() {
            return Ok(None);
        }
        let loopback_only = match mode {
            NetworkMode::Bridge => {
                return Err(NetError::new(
                    NetErrorCode::Unimplemented,
                    "--dns on bridge network is handled by DNS helper upstream forwarding (not implemented)",
                ));
            }
            NetworkMode::Host => false,
            NetworkMode::None => true,
        };
        let mut nameservers = Vec::with_capacity(dns.len());
        for s in dns {
            let ip = parse_ip_addr(s)?;
            if loopback_only && !ip.is_loopback() {
                return Err(InputViolation::NotLoopbackForNoneMode.into());
            }
            nameservers.push(ip);
        }
        Ok(Some(Self { nameservers }))
    }

    /// 書き込む nameserver（入力順・重複保持）。
    pub fn nameservers(&self) -> &[IpAddr] {
        &self.nameservers
    }

    /// ファイル本文（LF 固定。`IpAddr` の表記のみを使う）。
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        for ip in &self.nameservers {
            out.push_str(&format!("nameserver {ip}\n"));
        }
        out
    }

    /// 原子的に書き込む（呼び出しごとに固有の tmp + `create_new` + 0644 明示 + fsync + rename + 親ディレクトリ fsync）。
    ///
    /// 親ディレクトリの open / fsync に失敗した場合も `INTERNAL` を返す（rename 済みのため内容は置換済みだが、
    /// 永続化は保証されない）。
    ///
    /// 本文は高々 `MAX_DNS_SERVERS` 行なので追加の長さ検査は不要。失敗は固定メッセージの `INTERNAL`。
    pub fn write_to(&self, path: &Path) -> Result<(), NetError> {
        let werr = || NetError::new(NetErrorCode::Internal, "failed to write resolv.conf");
        // 呼び出しごとに固有の一時ファイル名（pid + プロセス内カウンタ + 時刻）を同一ディレクトリに作る。
        // 固定名だと同一 path への同時書き込みが互いの tmp を削除・上書きして壊れるため。
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.subsec_nanos())
            .unwrap_or(0);
        let mut tmp_name: OsString = path.as_os_str().to_owned();
        tmp_name.push(format!(
            ".tmp.{}.{}.{nanos}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed)
        ));
        let tmp = Path::new(&tmp_name);
        let mut opts = OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            // 作成時の初期値。umask で狭まりうるため、下で明示的に 0644 へ設定し直す。
            opts.mode(0o644);
        }
        let body = self.render();
        let result = (|| {
            let mut f = opts.open(tmp).map_err(|_| werr())?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                // コンテナ内の非 root プロセスが読めるよう、umask に関わらず 0644 を明示する。
                f.set_permissions(std::fs::Permissions::from_mode(0o644))
                    .map_err(|_| werr())?;
            }
            f.write_all(body.as_bytes()).map_err(|_| werr())?;
            f.sync_all().map_err(|_| werr())?;
            drop(f);
            std::fs::rename(tmp, path).map_err(|_| werr())
        })();
        if result.is_err() {
            let _ = std::fs::remove_file(tmp);
            return result;
        }
        // 永続化保証（親ディレクトリ fsync）に失敗した場合は成功を装わずエラーにする。
        #[cfg(unix)]
        if let Some(dir) = path.parent().filter(|d| !d.as_os_str().is_empty()) {
            std::fs::File::open(dir)
                .and_then(|d| d.sync_all())
                .map_err(|_| werr())?;
        }
        Ok(())
    }
}

/// 検証 → 書き込みを 1 呼び出しで行う入口。`Err` のときファイルに一切触れない。
pub fn apply_dns(
    mode: NetworkMode,
    dns: &[&str],
    path: &Path,
) -> Result<DnsApplyOutcome, NetError> {
    match ResolvConfPlan::for_mode(mode, dns)? {
        None => Ok(DnsApplyOutcome::NotRequested),
        Some(plan) => {
            plan.write_to(path)?;
            Ok(DnsApplyOutcome::Written {
                count: plan.nameservers().len(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    struct Dir(PathBuf);
    impl Dir {
        fn new(tag: &str) -> Self {
            let p = std::env::temp_dir().join(format!("fc-resolv-{tag}-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&p);
            std::fs::create_dir_all(&p).unwrap();
            Self(p)
        }
        fn file(&self) -> PathBuf {
            self.0.join("resolv.conf")
        }
    }
    impl Drop for Dir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn body(lines: &[&str]) -> String {
        let mut s = String::from(HEADER);
        for l in lines {
            s.push_str(&format!("nameserver {l}\n"));
        }
        s
    }

    fn assert_not_loopback(e: &NetError) {
        assert_eq!(e.code().as_str(), "INVALID_ARGUMENT");
        assert_eq!(
            e.message(),
            InputViolation::NotLoopbackForNoneMode.message()
        );
    }

    /// NET-12・TASK-185.4: host は検証済みの値を入力順に書き、既存ファイルを置換する。
    #[test]
    fn host_writes_nameservers() {
        let d = Dir::new("host");
        std::fs::write(d.file(), "old\n").unwrap();
        let out = apply_dns(
            NetworkMode::Host,
            &["192.0.2.53", "2001:db8::53"],
            &d.file(),
        )
        .unwrap();
        assert_eq!(out, DnsApplyOutcome::Written { count: 2 });
        assert_eq!(
            std::fs::read_to_string(d.file()).unwrap(),
            body(&["192.0.2.53", "2001:db8::53"])
        );
    }

    /// NET-12: IPv6 は正規表記で書かれる。
    #[test]
    fn host_normalizes_ipv6() {
        let plan = ResolvConfPlan::for_mode(NetworkMode::Host, &["2001:0db8::0053"])
            .unwrap()
            .unwrap();
        assert_eq!(plan.render(), body(&["2001:db8::53"]));
    }

    /// NET-6・NET-12: none は loopback のみ受理する。
    #[test]
    fn none_accepts_loopback() {
        for ip in ["127.0.0.1", "127.255.255.254", "::1"] {
            let d = Dir::new("noneok");
            let out = apply_dns(NetworkMode::None, &[ip], &d.file()).unwrap();
            assert_eq!(out, DnsApplyOutcome::Written { count: 1 });
            assert_eq!(std::fs::read_to_string(d.file()).unwrap(), body(&[ip]));
        }
    }

    /// NET-6・NET-12: none の非 loopback は ERR-1 形式で拒否し、既存ファイルも残骸も変えない。
    #[test]
    fn none_rejects_non_loopback_without_side_effect() {
        let d = Dir::new("nonerej");
        std::fs::write(d.file(), b"keep\n").unwrap();
        let e = apply_dns(NetworkMode::None, &["8.8.8.8"], &d.file()).unwrap_err();
        assert_not_loopback(&e);
        assert_eq!(std::fs::read(d.file()).unwrap(), b"keep\n");
        assert_eq!(std::fs::read_dir(&d.0).unwrap().count(), 1);
    }

    /// NET-6: loopback 境界。IPv4 射影・未指定アドレスも拒否（fail-closed）。
    #[test]
    fn none_rejects_boundaries() {
        for ip in [
            "128.0.0.1",
            "126.255.255.255",
            "::2",
            "::ffff:127.0.0.1",
            "0.0.0.0",
            "::",
        ] {
            let e = ResolvConfPlan::for_mode(NetworkMode::None, &[ip]).unwrap_err();
            assert_not_loopback(&e);
        }
    }

    /// NET-12: 1 件でも不正なら all-or-nothing でファイル不変、入力値はメッセージに載らない。
    #[test]
    fn all_or_nothing() {
        let d = Dir::new("aon");
        std::fs::write(d.file(), b"keep\n").unwrap();
        let e = apply_dns(NetworkMode::None, &["127.0.0.1", "8.8.8.8"], &d.file()).unwrap_err();
        assert_not_loopback(&e);
        let e = apply_dns(NetworkMode::Host, &["192.0.2.1", "bad\nvalue"], &d.file()).unwrap_err();
        assert_eq!(e.message(), InputViolation::ControlOrWhitespace.message());
        assert!(!e.message().contains("bad"));
        assert_eq!(std::fs::read(d.file()).unwrap(), b"keep\n");
    }

    /// NET-12: 件数上限（確保前に判定）。
    #[test]
    fn count_limit() {
        let ok = vec!["192.0.2.1"; MAX_DNS_SERVERS];
        assert!(
            ResolvConfPlan::for_mode(NetworkMode::Host, &ok)
                .unwrap()
                .is_some()
        );
        let over = vec!["192.0.2.1"; MAX_DNS_SERVERS + 1];
        let e = ResolvConfPlan::for_mode(NetworkMode::Host, &over).unwrap_err();
        assert_eq!(e.code().as_str(), "INVALID_ARGUMENT");
        assert_eq!(e.message(), "too many --dns servers");
    }

    /// NET-12: 空指定は no-op（既存ファイル不変・未作成なら作らない）。
    #[test]
    fn empty_is_noop() {
        let d = Dir::new("empty");
        for m in [NetworkMode::Host, NetworkMode::None] {
            assert_eq!(
                apply_dns(m, &[], &d.file()).unwrap(),
                DnsApplyOutcome::NotRequested
            );
            assert!(!d.file().exists());
        }
        std::fs::write(d.file(), b"keep\n").unwrap();
        apply_dns(NetworkMode::Host, &[], &d.file()).unwrap();
        assert_eq!(std::fs::read(d.file()).unwrap(), b"keep\n");
    }

    /// NET-12・REPAIR-3: bridge は未実装で nameserver を書かない。
    #[test]
    fn bridge_is_unimplemented() {
        let d = Dir::new("bridge");
        std::fs::write(d.file(), b"keep\n").unwrap();
        let e = apply_dns(NetworkMode::Bridge, &["192.0.2.1"], &d.file()).unwrap_err();
        assert_eq!(e.code().as_str(), "UNIMPLEMENTED");
        assert_eq!(std::fs::read(d.file()).unwrap(), b"keep\n");
    }

    /// NET-12: 書き込みは最終要素の symlink を追従せず置換し、0644 になる。
    #[cfg(unix)]
    #[test]
    fn write_does_not_follow_symlink() {
        use std::os::unix::fs::PermissionsExt;
        let d = Dir::new("sym");
        let target = d.0.join("target");
        std::fs::write(&target, b"victim\n").unwrap();
        std::os::unix::fs::symlink(&target, d.file()).unwrap();
        apply_dns(NetworkMode::Host, &["192.0.2.1"], &d.file()).unwrap();
        assert_eq!(std::fs::read(&target).unwrap(), b"victim\n");
        let md = std::fs::symlink_metadata(d.file()).unwrap();
        assert!(md.file_type().is_file());
        assert_eq!(md.permissions().mode() & 0o777, 0o644);
        assert_eq!(
            std::fs::read_to_string(d.file()).unwrap(),
            body(&["192.0.2.1"])
        );
    }

    /// NET-12: 既存が 0600 でも置換後は 0644 になり、tmp の残骸を残さない（set_permissions の明示）。
    #[cfg(unix)]
    #[test]
    fn mode_is_0644_over_restrictive_existing_file() {
        use std::os::unix::fs::PermissionsExt;
        // umask はプロセス全体に効くため、他テストへ影響しない代替として
        // 事前に 0600 の同名既存ファイルがあっても結果が 0644 になることを確認する。
        let d = Dir::new("mode");
        std::fs::write(d.file(), b"old\n").unwrap();
        std::fs::set_permissions(d.file(), std::fs::Permissions::from_mode(0o600)).unwrap();
        apply_dns(NetworkMode::Host, &["192.0.2.1"], &d.file()).unwrap();
        let md = std::fs::metadata(d.file()).unwrap();
        assert_eq!(md.permissions().mode() & 0o777, 0o644);
        assert_eq!(std::fs::read_dir(&d.0).unwrap().count(), 1);
    }

    /// NET-12: 同一 path への同時書き込みでも各呼び出しが成功し、最終内容はどちらかの完全な本文になる。
    #[test]
    fn concurrent_writes_do_not_corrupt() {
        let d = Dir::new("conc");
        let path = d.file();
        let handles: Vec<_> = (0..8)
            .map(|i| {
                let p = path.clone();
                std::thread::spawn(move || {
                    let ip = format!("192.0.2.{}", i + 1);
                    for _ in 0..20 {
                        apply_dns(NetworkMode::Host, &[ip.as_str()], &p).unwrap();
                    }
                })
            })
            .collect();
        for h in handles {
            h.join().unwrap();
        }
        let got = std::fs::read_to_string(&path).unwrap();
        assert!((1..=8).any(|i| got == body(&[&format!("192.0.2.{i}")])));
        assert_eq!(std::fs::read_dir(&d.0).unwrap().count(), 1);
    }

    /// NET-12: render は具体値。
    #[test]
    fn render_is_exact() {
        let plan = ResolvConfPlan::for_mode(NetworkMode::Host, &["192.0.2.1", "192.0.2.1"])
            .unwrap()
            .unwrap();
        assert_eq!(
            plan.render(),
            "# Generated by fandhe-container (NET-12)\nnameserver 192.0.2.1\nnameserver 192.0.2.1\n"
        );
    }
}
