//! `apply_dns` 公開 API の結合試験（NET-12・NET-6・TASK-185.4・#347・REPAIR-10・MS-8）。
//!
//! crate 外部から公開 API だけで host / none の `--dns` 反映とファイル内容を機械照合する。
//! 実ファイルシステム（一時ディレクトリ）のみを使い権限不要のため、3 OS の既定結合試験集合で実行する（ci.md）。

use std::path::PathBuf;

use fandhe_container_net::add_host_dns::resolv_conf::{
    DnsApplyOutcome, MAX_DNS_SERVERS, PersistGuarantee, ResolvConfPlan, apply_dns,
};
use fandhe_container_net::instrument::NoopNetOpRecorder;
use fandhe_container_net::network_mode::NetworkMode;

/// OS ごとの永続化保証（unix は親ディレクトリ fsync 済み、それ以外は内容のみ）。
#[cfg(unix)]
const PERSIST: PersistGuarantee = PersistGuarantee::Durable;
#[cfg(not(unix))]
const PERSIST: PersistGuarantee = PersistGuarantee::ContentOnly;

struct Dir(PathBuf);
impl Dir {
    fn new(tag: &str) -> Self {
        let p = std::env::temp_dir().join(format!("fc-resolv-it-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).expect("mkdir");
        Self(p)
    }
    fn file(&self) -> PathBuf {
        self.0.join("resolv.conf")
    }
}
impl Drop for Dir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// NET-12: host は入力順に nameserver 行を書き、既存ファイルを置換して一時ファイルを残さない。
#[test]
fn net12_host_writes_file() {
    let d = Dir::new("host");
    std::fs::write(d.file(), "old\n").expect("seed");
    let out = apply_dns(
        NetworkMode::Host,
        &["192.0.2.53", "2001:0db8::0053"],
        &d.file(),
        &NoopNetOpRecorder,
    )
    .expect("apply");
    assert_eq!(
        out,
        DnsApplyOutcome::Written {
            count: 2,
            persistence: PERSIST
        }
    );
    assert_eq!(
        std::fs::read_to_string(d.file()).expect("read"),
        "# Generated by fandhe-container (NET-12)\nnameserver 192.0.2.53\nnameserver 2001:db8::53\n"
    );
    assert_eq!(std::fs::read_dir(&d.0).expect("ls").count(), 1);
}

/// NET-6・NET-12: none は loopback のみ書き、非 loopback は INVALID_ARGUMENT でファイル不変。
#[test]
fn net6_none_loopback_only() {
    let d = Dir::new("none");
    let out = apply_dns(
        NetworkMode::None,
        &["127.0.0.1", "::1"],
        &d.file(),
        &NoopNetOpRecorder,
    )
    .expect("apply");
    assert_eq!(
        out,
        DnsApplyOutcome::Written {
            count: 2,
            persistence: PERSIST
        }
    );
    let expected =
        "# Generated by fandhe-container (NET-12)\nnameserver 127.0.0.1\nnameserver ::1\n";
    assert_eq!(std::fs::read_to_string(d.file()).expect("read"), expected);
    let e = apply_dns(
        NetworkMode::None,
        &["127.0.0.1", "8.8.8.8"],
        &d.file(),
        &NoopNetOpRecorder,
    )
    .unwrap_err();
    assert_eq!(e.code().as_str(), "INVALID_ARGUMENT");
    assert_eq!(std::fs::read_to_string(d.file()).expect("read"), expected);
}

/// NET-12: 空指定は no-op、bridge は UNIMPLEMENTED でファイルに触れない、件数超過は拒否。
#[test]
fn net12_noop_bridge_and_limit() {
    let d = Dir::new("misc");
    assert_eq!(
        apply_dns(NetworkMode::Host, &[], &d.file(), &NoopNetOpRecorder).expect("noop"),
        DnsApplyOutcome::NotRequested
    );
    assert!(!d.file().exists());
    let e = apply_dns(
        NetworkMode::Bridge,
        &["192.0.2.1"],
        &d.file(),
        &NoopNetOpRecorder,
    )
    .unwrap_err();
    assert_eq!(e.code().as_str(), "UNIMPLEMENTED");
    assert!(!d.file().exists());
    let over = vec!["192.0.2.1"; MAX_DNS_SERVERS + 1];
    let e = ResolvConfPlan::for_mode(NetworkMode::Host, &over).unwrap_err();
    assert_eq!(e.message(), "too many --dns servers");
}
